#!/bin/bash

curl https://bootstrap.pypa.io/pip/2.7/get-pip.py --output get-pip.py
python2 ./get-pip.py
git clone https://github.com/mrexodia/perfect-dll-proxy.git;  
cd perfect-dll-proxy
python2 -m pip install --upgrade setuptools pip==20.3.4;  
pip2 install -r requirements.txt; 
chmod +x perfect-dll-proxy.py; 
#echo "PATH=$PATH:/opt/perfect-dll-proxy/" >> /root/.bashrc

ln -s /bin/python3.13 /bin/python
wget https://bootstrap.pypa.io/get-pip.py



apt-get install -y python3-pip 
apt-get install -y pipx
git clone https://github.com/mrexodia/perfect-dll-proxy.git;  
cd perfect-dll-proxy
pip install -r requirements.txt; 

